package me.thanish.prayers.se.routes.compass.components

import android.location.Location
import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.sin

/**
 * A helper to calculate the Qibla direction.
 */
object CurrentQibla {
    /**
     * The coordinates of the Qibla in radians.
     */
    private val MAKKAH_LAT = Math.toRadians(21.4225)
    private val MAKKAH_LON = Math.toRadians(39.8262)

    /**
     * Calculates the Qibla direction (angle in degrees) relative to North.
     * TODO: This calculation code is generated by Gemini, should be verified
     */
    fun getQiblaDirection(location: Location?): Float? {
        if (location == null) {
            return null
        }
        val lat = Math.toRadians(location.latitude)
        val lon = Math.toRadians(location.longitude)

        val y = sin(MAKKAH_LON - lon) * cos(MAKKAH_LAT)
        val x = cos(lat) * sin(MAKKAH_LAT) - sin(lat) * cos(MAKKAH_LAT) * cos(MAKKAH_LON - lon)

        return normalizeAngle(atan2(y, x).toFloat())
    }
}
