/**
 * List of cities supported by the library.
 */
export const CITIES = [
  'alingsås',
  'åmål',
  'ängelholm',
  'avesta',
  'bengtsfors',
  'boden',
  'bollnäs',
  'borås',
  'borlänge',
  'eksjö',
  'enköping',
  'eskilstuna',
  'eslöv',
  'falkenberg',
  'falköping',
  'filipstad',
  'flen',
  'gällivare',
  'gävle',
  'gislaved',
  'gnosjö',
  'göteborg',
  'halmstad',
  'haparanda',
  'härnösand',
  'hässleholm',
  'helsingborg',
  'högsby',
  'hörby',
  'hudiksvall',
  'hultsfred',
  'jokkmokk',
  'jönköping',
  'kalmar',
  'kalrshamn',
  'karlskoga',
  'karlskrona',
  'karlstad',
  'katrineholm',
  'kiruna',
  'köping',
  'kristianstad',
  'kristinehamn',
  'laholm',
  'landskrona',
  'lessebo',
  'lidköping',
  'linköping',
  'ludvika',
  'luleå',
  'lund',
  'lysekil',
  'malmö',
  'mariestad',
  'märsta',
  'mellerud',
  'mjölby',
  'mönsterås',
  'munkedal',
  'nässjö',
  'norrköping',
  'norrtälje',
  'nybro',
  'nyköping',
  'nynäshamn',
  'örebro',
  'örnsköldsvik',
  'oskarshamn',
  'östersund',
  'oxelösund',
  'pajala',
  'piteå',
  'ronneby',
  'säffle',
  'sala',
  'sävsjö',
  'simrishamn',
  'skara',
  'skellefteå',
  'skövde',
  'söderhamn',
  'södertälje',
  'sollefteå',
  'sölvesborg',
  'stockholm',
  'strängnäs',
  'sundsvall',
  'tierp',
  'tranemo',
  'trelleborg',
  'trollhättan',
  'uddevalla',
  'ulricehamn',
  'umeå',
  'uppsala',
  'vänersborg',
  'varberg',
  'värnamo',
  'västerås',
  'västervik',
  'växjö',
  'vetlanda',
  'vimmerby',
  'visby',
  'ystad',
] as const;

/**
 * Default city to use if none is provided.
 */
export const DEFAULT_CITY: City = 'stockholm';

/**
 * Type for cities supported by the library.
 */
export type City = (typeof CITIES)[number];

/**
 * Check if the given value is a valid city.
 */
export function isValidCity(city: any): city is City {
  return CITIES.includes(city);
}
