name: publish api database

on:
  push:
    branches:
      - main
    paths:
      - "data/**"
      - "apps/webapi/**"
  workflow_dispatch:

jobs:
  sync-db:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/webapi

    steps:
      - name: checkout repository
        uses: actions/checkout@v7

      - name: setup node
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: run database sync
        run: bun run db:update
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: wait for API update
        run: sleep 5

      - name: verify API version
        run: bun run db:verify
